export {
  createWorkspace,
  createWorkspaceFile,
  createWorkspaceFolder,
  deleteWorkspaceObject,
  getWorkspaceObjectContent,
  getWorkspaceObjectVersionContent,
  listWorkspaceObjectVersions,
  listWorkspaces,
  listWorkspaceTree,
  renameMoveWorkspaceObject,
  restoreWorkspaceObjectVersion,
  updateWorkspaceObjectContent,
  type Workspace,
  type WorkspaceObject,
  type WorkspaceObjectContentResponse,
  type WorkspaceObjectVersion,
  type WorkspaceTreeResponse,
} from "@/lib/api/gateway-client"
